version: "3.0"
services:
  db:
    image: mysql/mysql-server:8.0.23
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_USERNAME}
    ports:
      - 3306:3306
  sprint:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
