spring:
  datasource:
    url: jdbc:mysql://${MYSQL_URL}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: "dlawjddn"
      password: "dlawjddn"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

security:
  oauth:
    github:
      client-id: ${GITHUB_CLIENT_ID}
      client-secret: ${GITHUB_CLIENT_SECRET}
jwt:
  secret: ${JWT_SECRET}
  access-token:
    expiration: ${TOKEN_EXPIRATION}
  refresh-token:
    expiration: ${REFRESH_EXPIRATION}
